### ISSUE TITLE
Support for v14 and different default port

### ISSUE THREAD

**Issue by krumpaul** [joel74/POSH-LTM-Rest#175]
We recently deployed a couple f5's in azure and are unable to manage these f5's through powershell. Azure deploy's the marketplace f5's with a default port of 8443 and v14. We believe that this is more related to the non-443 port more than version as it appears both the BaseURL and AuthURL work correctly when manually called  

https://IP:8443/mgmt/tm/ltm/
RETURNS:  {"kind":"tm:ltm:ltmcollectionstate","selfLink":"https://localhost/mgmt/tm/ltm?ver=14.0.0.1"

https://IP:8443/mgmt/shared/authn/login
Is also correct

The below code will error with: "The Specified LTM name IP:8443 is not valid."

`$secpasswd = ConvertTo-SecureString "XXXXXXXXXXXXXXXXXXXX" -AsPlainText -Force
$mycreds = New-Object System.Management.Automation.PSCredential "YYYYYYYYYYY", $secpasswd
$MyLTM_IP = 'IP:8443'
New-F5Session -LTMName $MyLTM_IP -LTMCredentials $mycreds`

**Comment by joel74** [comment]
Hi, I'm working on getting my hands on a license for v14, but in the meantime I'll troubleshoot as I'm able via proxy. You've created the two variables that the New-F5Session cmdlet needs. You could try executing these lines and see what error it generates. I'm curious if you're able to get a token or if something with the structure of that changed.

[code within New-F5Session.txt](https://github.com/joel74/POSH-LTM-Rest/files/2511550/code.within.New-F5Session.txt)

**Comment by krumpaul** [comment]
Did some testing while using New-F5Session manually. Potential Fix below as well.   It is failing on InvokeRestMethodOverride. So I put a try catch on 

> $Result = Invoke-RestMethodOverride -Method POST -Uri $AuthURL -Body $JSONBody -Credential $LTMCredentials -ContentType 'application/json' `

The Returned results from the try catch:

> Status         : SendFailure
Response       : 
Message        : The underlying connection was closed: An unexpected error occurred on a send.
Data           : {}
InnerException : System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
                    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
                    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
                    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
                    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
                    at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
                    at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
                    at System.Net.ConnectStream.WriteHeaders(Boolean async)
TargetSite     : System.Net.WebResponse GetResponse(System.Net.WebRequest)
StackTrace     :    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
HelpLink       : 
Source         : Microsoft.PowerShell.Commands.Utility
HResult        : -2146233079


I then tested posting manually through Postman using the information your powershell generates and it returned correct results so it had to be something with how Powershell made the request through Invoke-RestMethod.  Turns out that even on server 2016( and win10) Invoke-RestMethod only tries TLS1.0 and nothing higher by default.  

ADDED THE FOLLOWING TO THE TOP OF OUR SCRIPTS AND IT RESOLVED THE ISSUE:

> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Source: https://forum.playcanvas.com/t/solved-connection-closed-when-using-powershells-invoke-restmethod-on-playcanvas-urls/4278/5


We successfully ran scripts using the above change on older ltm devices running v12.1.3.2

**Comment by joel74** [comment]
Nice find! It's curious that it seems to default to TLS 1.0 instead of trying 1.1 or 1.2 (I'm assuming they were initially enabled in .NET framework). Sounds like a fix that should be baked into the module so that all new sessions are attempted using TLS 1.2. Thanks for testing and sharing.

**Comment by joel74** [comment]
see PR #174
